---
- name: Saltar rol appservice en CI
  meta: end_play
  when: deploy is not defined

- name: Validar que el ZIP generado existe
  ansible.builtin.stat:
    path: "{{ lookup('env','ZIP_PATH') }}"
  register: zip_file

- name: Fallar si el ZIP no existe
  fail:
    msg: "El ZIP del microservicio no existe en {{ zip_path }}"
  when:
    - deploy is defined
    - not zip_file.stat.exists
- name: Validar que el archivo main.py existe dentro del repo
  ansible.builtin.stat:
    path: "./main.py"
  register: main_file

- name: Fallar si main.py no existe
  ansible.builtin.fail:
    msg: "main.py no existe en el repositorio"
  when: not main_file.stat.exists
