---
- name: Validación y pruebas EcoAnalyzer PRE/PRO
  hosts: ecoanalyzer
  gather_facts: false


  roles:
    - {role: validate, when: deploy is defined}
    - {role: appservice, when: deploy is defined}
    - tests
